//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectD01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public Nullable<int> floor { get; set; }
        public Nullable<int> price { get; set; }
        public string status { get; set; }
        public Nullable<int> room_no { get; set; }
        public Nullable<int> noOfPeople { get; set; }
        public Nullable<System.DateTime> startingDate { get; set; }
        public Nullable<System.DateTime> endingDate { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual User User { get; set; }
    }
}
